version: "3.3"
services:
  api:
    image: golang:1.16.0
    command: sh -c "cd cmd && go run main.go"
    environment:
     - DEBIAN_FRONTEND=nonintercative
     - GO111MODULE=on
    volumes:
     - type: volume
       source: ./meander
       target: /go/src/meander
    working_dir: /go/src/meander
    ports:
     - "127.0.0.1:8080:8080"
  web:
    image: golang:1.16.0
    command: sh -c "go run main.go"
    environment:
     - DEBIAN_FRONTEND=nonintercative
     - GO111MODULE=on
    volumes:
     - type: volume
       source: ./meanderweb
       target: /go/src/meanderweb
    working_dir: /go/src/meanderweb
    ports:
     - "127.0.0.1:8081:8081"
